---
- name: install packages maven,git,tomcat8
  hosts: web
  become: yes

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure java jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat8 package is present
    apt:
      name: tomcat8
      state: present

  - name: Ensure git is present
    apt:
      name: git
      state: present

  - name: Ensure maven is present
    apt:
      name: maven
      state: present
  
  - name: git clone boxfuse
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/boxfuse
